import { db } from "@/lib/db/client";
import { jakartaDayRange } from "@/lib/date/jakarta";
import { rankSmartTasks, priorityScore } from "@/lib/smart-today/scoring";
import type { TaskDiscovery } from "@/lib/validation/task-discovery";
import { taskProgress } from "@/server/services/task-service";
const include = { project: { select: { id: true, name: true, area: { select: { name: true } } } }, subtasks: { orderBy: [{ position: "asc" as const }, { createdAt: "asc" as const }] } };
export function getTasksForUser(userId: string) { return db.task.findMany({ where: { userId, deletedAt: null }, orderBy: [{ status: "asc" }, { deadlineAt: "asc" }, { createdAt: "desc" }], include }); }
export function getTaskByIdForUser(userId: string, id: string) { return db.task.findFirst({ where: { id, userId, deletedAt: null }, include }); }
export function getAssignableProjects(userId: string) { return db.project.findMany({ where: { userId, deletedAt: null, status: { not: "ARCHIVED" } }, orderBy: { name: "asc" }, select: { id: true, name: true } }); }

export async function getTaskDiscoveryOptions(userId:string){const[projects,areas]=await Promise.all([db.project.findMany({where:{userId,deletedAt:null,status:{not:"ARCHIVED"}},orderBy:{name:"asc"},select:{id:true,name:true}}),db.area.findMany({where:{userId,deletedAt:null},orderBy:[{position:"asc"},{name:"asc"}],select:{id:true,name:true}})]);return{projects,areas}}
export async function getFilteredTasks(userId:string,filters:TaskDiscovery,now:Date,today:string){const{start,end}=jakartaDayRange(today),deadlineWhere=filters.deadline==="TODAY"?{gte:start,lt:end}:filters.deadline==="UPCOMING"?{gte:end}:filters.deadline==="OVERDUE"?{lt:now}:filters.deadline==="NONE"?null:undefined,statuses:TaskDiscovery["statuses"]=filters.deadline==="OVERDUE"?(filters.statuses.length?filters.statuses.filter(status=>status!=="DONE"):["TODO","IN_PROGRESS"]):filters.statuses;const tasks=await db.task.findMany({where:{userId,deletedAt:null,title:filters.q?{contains:filters.q,mode:"insensitive"}:undefined,status:statuses.length?{in:statuses}:filters.deadline==="OVERDUE"?{in:[]}:undefined,priority:filters.priorities.length?{in:filters.priorities}:undefined,projectId:filters.projectId??undefined,project:filters.areaId?{areaId:filters.areaId,userId,deletedAt:null}:undefined,deadlineAt:deadlineWhere},include:{...include,timeBlocks:{where:{deletedAt:null,startAt:{lt:end},endAt:{gt:start}},select:{id:true}}},orderBy:filters.sort==="DEFAULT"?[{status:"asc"},{deadlineAt:"asc"},{createdAt:"desc"}]:{id:"asc"}});if(filters.sort==="DEADLINE")return tasks.sort((a,b)=>(a.deadlineAt?.getTime()??Infinity)-(b.deadlineAt?.getTime()??Infinity)||a.id.localeCompare(b.id));if(filters.sort==="PRIORITY")return tasks.sort((a,b)=>priorityScore(b.priority)-priorityScore(a.priority)||a.id.localeCompare(b.id));if(filters.sort==="CREATED")return tasks.sort((a,b)=>b.createdAt.getTime()-a.createdAt.getTime()||a.id.localeCompare(b.id));if(filters.sort==="SMART")return rankSmartTasks(tasks.map(task=>({...task,progress:taskProgress(task).progress,scheduledToday:task.timeBlocks.length>0})),now,today);return tasks}
export function countActiveTasks(userId:string){return db.task.count({where:{userId,deletedAt:null}})}
export function getTrashedTasks(userId:string){return db.task.findMany({where:{userId,deletedAt:{not:null}},include:{project:{select:{name:true}}},orderBy:[{deletedAt:"desc"},{id:"asc"}]})}
