import { jakartaDate, jakartaInputParts } from "@/lib/date/jakarta";
import { requireUser } from "@/lib/auth/session";
import { EventForm } from "@/components/event-form";
import { createEventAction, deleteEventAction, updateEventAction } from "@/server/actions/events";
import { getEvents } from "@/server/queries/event-queries";
import { eventTemporalState } from "@/server/services/event-service";

const fmt=(date:Date)=>new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"}).format(date);
export default async function EventsPage(){const user=await requireUser(),events=await getEvents(user.id);return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><header><p className="text-sm font-semibold text-emerald-700">SCHEDULE</p><h1 className="mt-2 text-4xl font-semibold">Events</h1><p className="mt-2 text-slate-600">Kelola acara satu kali dan rangkaian mingguan. Acara tidak memiliki status selesai.</p></header><section className="mt-10 border-t border-slate-200 pt-8"><h2 className="text-xl font-semibold">Acara baru</h2><div className="mt-5 max-w-3xl"><EventForm action={createEventAction} date={jakartaDate()}/></div></section><section className="mt-12 border-t border-slate-200 pt-8"><h2 className="text-xl font-semibold">Acara aktif</h2>{events.length===0?<p className="mt-4 text-slate-500">Belum ada acara. Tambahkan jadwal tetap atau acara satu kali.</p>:<div className="mt-5 grid gap-5">{events.map(event=><article key={event.id} className="rounded-xl border border-slate-200 bg-white p-5"><div className="flex flex-wrap items-start justify-between gap-3"><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold">{event.title}</h3>{event.recurrenceRule?<span className="rounded-full bg-emerald-50 px-2 py-1 text-xs text-emerald-800">Berulang</span>:null}<span className="text-xs text-slate-500">{eventTemporalState(event)}</span></div><p className="mt-1 text-sm text-slate-600">{fmt(event.startAt)}–{new Intl.DateTimeFormat("id-ID",{timeStyle:"short",timeZone:"Asia/Jakarta"}).format(event.endAt)}</p>{event.location?<p className="mt-1 text-sm">{event.location}</p>:null}{event.notes?<p className="mt-2 text-sm text-slate-600">{event.notes}</p>:null}{event.recurrenceRule?<p className="mt-2 text-xs text-slate-500">Setiap {event.recurrenceRule.interval} minggu · {event.recurrenceRule.daysOfWeek.join(", ")}{event.recurrenceRule.until?` · sampai ${event.recurrenceRule.until.toISOString().slice(0,10)}`:""}</p>:null}</div><form action={deleteEventAction}><input type="hidden" name="id" value={event.id}/><button className="min-h-11 rounded-lg border border-red-200 px-3 text-sm text-red-700">{event.recurrenceRule?"Hapus seluruh rangkaian":"Hapus acara"}</button></form></div><details className="mt-5 border-t pt-4"><summary className="cursor-pointer text-sm font-medium">{event.recurrenceRule?"Edit seluruh rangkaian":"Edit acara"}</summary><div className="mt-4"><EventForm action={updateEventAction} date={jakartaInputParts(event.startAt).date} event={event}/></div></details></article>)}</div>}</section></main>}
