import Link from "next/link";
import { requireUser } from "@/lib/auth/session";
import { calendarRange, navigateCalendar, validCalendarDate, type CalendarView } from "@/lib/date/calendar-range";
import { jakartaDate } from "@/lib/date/jakarta";
import { CalendarAgenda, CalendarMonth, CalendarWeek } from "@/components/calendar-views";
import { CalendarResponsiveDefault } from "@/components/calendar-responsive-default";
import { getCalendarItemsForRange } from "@/server/queries/calendar-queries";
const views:CalendarView[]=["month","week","day"];
export default async function CalendarPage({searchParams}:{searchParams:Promise<{view?:string;date?:string}>}){const[user,params]=await Promise.all([requireUser(),searchParams]),today=jakartaDate(),date=validCalendarDate(params.date,today),explicit=views.includes(params.view as CalendarView),view=explicit?params.view as CalendarView:"week",range=calendarRange(view,date),items=await getCalendarItemsForRange(user.id,range.start,range.end),previous=navigateCalendar(view,date,-1),next=navigateCalendar(view,date,1),href=(nextView:CalendarView,nextDate=date)=>`/calendar?view=${nextView}&date=${nextDate}`;return <main className="mx-auto max-w-7xl px-4 py-10 sm:px-6">{!explicit?<CalendarResponsiveDefault date={date}/>:null}<header className="flex flex-wrap items-end justify-between gap-5"><div><p className="text-sm font-semibold text-emerald-700">TIME</p><h1 className="mt-2 text-4xl font-semibold">Calendar</h1><p className="mt-2 text-slate-600">Event, Time Block, dan deadline dalam satu tampilan.</p></div><div className="flex rounded-lg border bg-white p-1" aria-label="Pilih tampilan">{views.map(option=><Link key={option} href={href(option)} className={`min-h-11 rounded-md px-4 py-2.5 text-sm font-medium capitalize ${view===option?"bg-slate-900 text-white":"text-slate-600"}`}>{option}</Link>)}</div></header><nav aria-label="Navigasi tanggal" className="my-7 flex flex-wrap items-center justify-between gap-3"><Link aria-label="Periode sebelumnya" href={href(view,previous)} className="min-h-11 rounded-lg border bg-white px-4 py-2.5">← Sebelumnya</Link><Link href={href(view,today)} className="min-h-11 rounded-lg border bg-white px-4 py-2.5 font-medium">Hari ini</Link><Link aria-label="Periode berikutnya" href={href(view,next)} className="min-h-11 rounded-lg border bg-white px-4 py-2.5">Berikutnya →</Link></nav>{!explicit?<><div className="md:hidden"><CalendarAgenda date={date} items={items}/></div><div className="hidden md:block"><CalendarWeek days={range.days} items={items} today={today}/></div></>:view==="month"?<CalendarMonth days={range.days} selectedDate={date} today={today} items={items}/>:view==="week"?<CalendarWeek days={range.days} items={items} today={today}/>:<CalendarAgenda date={date} items={items}/>}<div className="mt-8 flex flex-wrap gap-3 border-t pt-6 text-sm"><Link className="font-medium text-emerald-800" href="/events">Kelola Events</Link><Link className="font-medium text-sky-800" href="/planner">Buka Planner</Link><Link className="font-medium text-amber-800" href="/tasks">Lihat Tasks</Link></div></main>}
