"use server";
import { revalidatePath } from "next/cache"; import { redirect } from "next/navigation";
import { requireUser } from "@/lib/auth/session"; import { subtaskSchema, taskInputSchema, taskStatusSchema } from "@/lib/validation/task"; import type { FormState } from "./areas";
import { changeTaskStatus, createSubtask, createTask, deleteSubtask, deleteTask, permanentlyDeleteTask, restoreTask, TaskRuleError, toggleSubtask, updateSubtask, updateTask } from "@/server/services/task-service";
function values(f: FormData) { return { title:f.get("title"),description:f.get("description"),projectId:f.get("projectId"),deadlineDate:f.get("deadlineDate"),deadlineTime:f.get("deadlineTime"),priority:f.get("priority"),estimatedMinutes:f.get("estimatedMinutes") }; }
export async function createTaskAction(_:FormState,f:FormData):Promise<FormState>{const u=await requireUser(),p=taskInputSchema.safeParse(values(f));if(!p.success)return{error:null,fieldErrors:p.error.flatten().fieldErrors};try{await createTask(u.id,p.data)}catch(e){return{error:e instanceof TaskRuleError?e.message:"Tugas tidak dapat disimpan.",fieldErrors:{}}}revalidatePath("/tasks");return{error:null,fieldErrors:{},success:true}}
export async function updateTaskAction(_:FormState,f:FormData):Promise<FormState>{const u=await requireUser(),id=String(f.get("id")),p=taskInputSchema.safeParse(values(f));if(!p.success)return{error:null,fieldErrors:p.error.flatten().fieldErrors};try{if(!await updateTask(u.id,id,p.data))return{error:"Tugas tidak ditemukan.",fieldErrors:{}}}catch(e){return{error:e instanceof TaskRuleError?e.message:"Tugas tidak dapat disimpan.",fieldErrors:{}}}revalidatePath("/tasks");revalidatePath(`/tasks/${id}`);return{error:null,fieldErrors:{},success:true}}
export async function statusTaskAction(_:FormState,f:FormData):Promise<FormState>{const u=await requireUser(),id=String(f.get("id")),p=taskStatusSchema.safeParse(f.get("status"));if(!p.success)return{error:"Status tidak valid.",fieldErrors:{}};try{if(!await changeTaskStatus(u.id,id,p.data))return{error:"Tugas tidak ditemukan.",fieldErrors:{}}}catch(e){return{error:e instanceof TaskRuleError?e.message:"Status tidak dapat diubah.",fieldErrors:{}}}revalidatePath("/tasks");revalidatePath(`/tasks/${id}`);revalidatePath("/projects");return{error:null,fieldErrors:{},success:true}}
export async function deleteTaskAction(f:FormData){const u=await requireUser();await deleteTask(u.id,String(f.get("id")));revalidatePath("/tasks");revalidatePath("/trash");revalidatePath("/projects");revalidatePath("/today");revalidatePath("/calendar");revalidatePath("/planner");redirect("/tasks")}
export async function restoreTaskAction(f:FormData){const u=await requireUser();await restoreTask(u.id,String(f.get("id")));revalidatePath("/tasks");revalidatePath("/trash");revalidatePath("/projects");revalidatePath("/today");revalidatePath("/calendar");revalidatePath("/planner")}
export async function permanentlyDeleteTaskAction(f:FormData){const u=await requireUser();if(f.get("confirmation")!=="PERMANENT_DELETE")return;await permanentlyDeleteTask(u.id,String(f.get("id")));revalidatePath("/trash");revalidatePath("/reviews")}
export async function createSubtaskAction(_:FormState,f:FormData):Promise<FormState>{const u=await requireUser(),p=subtaskSchema.safeParse({title:f.get("title")}),taskId=String(f.get("taskId"));if(!p.success)return{error:null,fieldErrors:p.error.flatten().fieldErrors};if(!await createSubtask(u.id,taskId,p.data.title))return{error:"Tugas tidak ditemukan.",fieldErrors:{}};revalidatePath(`/tasks/${taskId}`);return{error:null,fieldErrors:{},success:true}}
export async function updateSubtaskAction(f:FormData){const u=await requireUser(),p=subtaskSchema.safeParse({title:f.get("title")});if(p.success)await updateSubtask(u.id,String(f.get("id")),p.data.title);revalidatePath(`/tasks/${String(f.get("taskId"))}`)}
export async function toggleSubtaskAction(f:FormData){const u=await requireUser();await toggleSubtask(u.id,String(f.get("id")));revalidatePath(`/tasks/${String(f.get("taskId"))}`)}
export async function deleteSubtaskAction(f:FormData){const u=await requireUser();await deleteSubtask(u.id,String(f.get("id")));revalidatePath(`/tasks/${String(f.get("taskId"))}`)}
