import Link from "next/link";
import { jakartaInputParts } from "@/lib/date/jakarta";
import type { CalendarItem } from "@/server/queries/calendar-queries";

const labels={EVENT:"Event",TIME_BLOCK:"Time Block",TASK_DEADLINE:"Deadline"} as const;
const tones={EVENT:"border-emerald-200 bg-emerald-50",TIME_BLOCK:"border-sky-200 bg-sky-50",TASK_DEADLINE:"border-amber-200 bg-amber-50"} as const;
const time=(date:Date)=>new Intl.DateTimeFormat("id-ID",{hour:"2-digit",minute:"2-digit",hour12:false,timeZone:"Asia/Jakarta"}).format(date);
const dayLabel=(date:string,full=false)=>new Intl.DateTimeFormat("id-ID",full?{dateStyle:"full",timeZone:"Asia/Jakarta"}:{weekday:"short",day:"numeric",timeZone:"Asia/Jakarta"}).format(new Date(`${date}T00:00:00+07:00`));
function Item({item,compact=false}:{item:CalendarItem;compact?:boolean}){return <Link href={item.href} className={`block min-w-0 max-w-full rounded-lg border p-2 text-left focus-visible:outline-2 focus-visible:outline-offset-2 ${tones[item.type]}`}><span className="block text-[11px] font-semibold uppercase tracking-wide">{labels[item.type]}{item.isRecurring?" · Berulang":""}</span><span className="block truncate text-sm font-semibold">{time(item.startAt)} {item.title}</span>{!compact?<><span className="block text-xs text-slate-600">{item.endAt?`sampai ${time(item.endAt)}`:"Tepat waktu"}</span>{item.context?<span className="block truncate text-xs text-slate-500">{item.context}</span>:null}</>:null}</Link>}
function byDay(items:CalendarItem[]){const map=new Map<string,CalendarItem[]>();for(const item of items){const key=jakartaInputParts(item.startAt).date;map.set(key,[...(map.get(key)??[]),item])}return map}
export function CalendarAgenda({date,items}:{date:string;items:CalendarItem[]}){const visible=items.filter(item=>jakartaInputParts(item.startAt).date===date);return <section aria-label="Agenda harian"><h2 className="text-lg font-semibold">{dayLabel(date,true)}</h2>{visible.length?<div className="mt-4 grid gap-3">{visible.map(item=><Item key={item.id} item={item}/>)}</div>:<p className="mt-5 rounded-xl border border-dashed p-6 text-center text-slate-500">Tidak ada jadwal pada hari ini.</p>}</section>}
export function CalendarWeek({days,items,today}:{days:string[];items:CalendarItem[];today:string}){const grouped=byDay(items);return <section aria-label="Calendar minggu" className="overflow-x-auto"><div className="grid min-w-[900px] grid-cols-7 gap-px rounded-xl border bg-slate-200">{days.map(date=><div key={date} className="min-h-[34rem] bg-white"><header className={`sticky top-0 z-10 border-b p-3 text-center text-sm font-semibold ${date===today?"bg-emerald-50 text-emerald-800":"bg-white"}`}>{dayLabel(date)}</header><div className="grid gap-2 p-2" style={{backgroundImage:"repeating-linear-gradient(to bottom, transparent 0, transparent 23px, #e2e8f0 24px)",backgroundSize:"100% 24px"}}>{(grouped.get(date)??[]).map(item=><Item key={item.id} item={item}/>)}</div></div>)}</div>{items.length===0?<p className="mt-4 text-center text-slate-500">Tidak ada jadwal pada minggu ini.</p>:null}</section>}
export function CalendarMonth({days,selectedDate,today,items}:{days:string[];selectedDate:string;today:string;items:CalendarItem[]}){const grouped=byDay(items),month=selectedDate.slice(0,7);return <section aria-label="Calendar bulan"><div className="grid grid-cols-7 text-center text-xs font-semibold uppercase tracking-wide text-slate-500">{["Sen","Sel","Rab","Kam","Jum","Sab","Min"].map(day=><div className="py-2" key={day}>{day}</div>)}</div><div className="grid grid-cols-7 gap-px overflow-hidden rounded-xl border bg-slate-200">{days.map(date=>{const list=grouped.get(date)??[];return <div key={date} className={`min-h-28 bg-white p-1.5 sm:min-h-36 sm:p-2 ${date.slice(0,7)!==month?"text-slate-400":""}`}><Link aria-label={`Buka ${date}`} href={`/calendar?view=day&date=${date}`} className={`inline-flex h-7 w-7 items-center justify-center rounded-full text-xs font-semibold ${date===today?"bg-emerald-700 text-white":date===selectedDate?"ring-2 ring-slate-400":""}`}>{Number(date.slice(-2))}</Link><div className="mt-1 grid gap-1">{list.slice(0,3).map(item=><Item compact key={item.id} item={item}/>)}{list.length>3?<Link className="text-xs font-medium text-slate-600" href={`/calendar?view=day&date=${date}`}>+{list.length-3} lainnya</Link>:null}</div></div>})}</div></section>}
