import "dotenv/config";
import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { calendarRange, navigateCalendar, validCalendarDate } from "@/lib/date/calendar-range";
import { db } from "@/lib/db/client";
import { getCalendarItemsForRange } from "@/server/queries/calendar-queries";
import { createEvent } from "./event-service";
import { createTask } from "./task-service";
import { createTimeBlock } from "./time-block-service";

const token=randomUUID();let owner:string,other:string;const start=new Date("2026-10-05T00:00:00+07:00"),end=new Date("2026-10-12T00:00:00+07:00");
describe("unified calendar",()=>{
  beforeAll(async()=>{const users=await Promise.all(["owner","other"].map(name=>db.user.create({data:{username:`calendar-${name}-${token}`,passwordHash:"$argon2id$test"}})));owner=users[0].id;other=users[1].id});
  afterAll(async()=>{const ids=[owner,other],rules=(await db.event.findMany({where:{userId:{in:ids},recurrenceRuleId:{not:null}},select:{recurrenceRuleId:true}})).flatMap(item=>item.recurrenceRuleId?[item.recurrenceRuleId]:[]);await db.timeBlock.deleteMany({where:{userId:{in:ids}}});await db.event.deleteMany({where:{userId:{in:ids}}});await db.recurrenceRule.deleteMany({where:{id:{in:rules}}});await db.task.deleteMany({where:{userId:{in:ids}}});await db.user.deleteMany({where:{id:{in:ids}}})});
  it("builds Jakarta day, Monday week, and visible month ranges with stable navigation",()=>{expect(calendarRange("day","2026-09-29").days).toEqual(["2026-09-29"]);expect(calendarRange("week","2026-09-29").days).toEqual(["2026-09-28","2026-09-29","2026-09-30","2026-10-01","2026-10-02","2026-10-03","2026-10-04"]);const month=calendarRange("month","2026-09-29");expect(month.days[0]).toBe("2026-08-31");expect(month.days.at(-1)).toBe("2026-10-04");expect(navigateCalendar("month","2026-03-31",-1)).toBe("2026-02-28");expect(validCalendarDate("banana","2026-09-29")).toBe("2026-09-29");expect(validCalendarDate("2026-02-31","2026-09-29")).toBe("2026-09-29")});
  it("normalizes one-time, recurring, standalone, linked, and exact-time deadline sources",async()=>{const task=await createTask(owner,{title:"Exact deadline",description:null,projectId:null,deadlineDate:"2026-10-05",deadlineTime:"14:30",priority:"HIGH",estimatedMinutes:null});await createEvent(owner,{title:"One event",date:"2026-10-05",startTime:"08:00",endTime:"09:00",location:"Room",notes:null,recurring:false,interval:1,daysOfWeek:[],until:""});const recurring=await createEvent(owner,{title:"Weekly",date:"2026-10-05",startTime:"10:00",endTime:"11:00",location:null,notes:null,recurring:true,interval:1,daysOfWeek:["MONDAY"],until:""});await createTimeBlock(owner,{title:"Standalone",taskId:null,date:"2026-10-05",startTime:"12:00",endTime:"13:00"});await createTimeBlock(owner,{title:"Linked",taskId:task.id,date:"2026-10-05",startTime:"13:00",endTime:"14:00"});const items=await getCalendarItemsForRange(owner,start,end);expect(new Set(items.map(item=>item.type))).toEqual(new Set(["EVENT","TIME_BLOCK","TASK_DEADLINE"]));expect(items.find(item=>item.id===`deadline:${task.id}`)?.startAt.toISOString()).toBe("2026-10-05T07:30:00.000Z");expect(items.find(item=>item.sourceId===recurring.id)?.id).toContain(recurring.id);expect(items.map(item=>item.startAt.getTime())).toEqual(items.map(item=>item.startAt.getTime()).toSorted((a,b)=>a-b));expect(await db.event.count({where:{id:recurring.id}})).toBe(1)});
  it("preserves the Phase 4 date-only deadline at 23:59 Jakarta and includes DONE tasks",async()=>{const task=await createTask(owner,{title:"Date only",description:null,projectId:null,deadlineDate:"2026-10-06",deadlineTime:"",priority:"MEDIUM",estimatedMinutes:null});await db.task.update({where:{id:task.id},data:{status:"DONE",completedAt:new Date()}});const item=(await getCalendarItemsForRange(owner,start,end)).find(value=>value.id===`deadline:${task.id}`);expect(item?.startAt.toISOString()).toBe("2026-10-06T16:59:00.000Z");expect(item?.endAt).toBeNull()});
  it("enforces ownership and deleted visibility while retaining overlapping active items",async()=>{const hiddenTask=await createTask(owner,{title:"Trashed",description:null,projectId:null,deadlineDate:"2026-10-07",deadlineTime:"09:00",priority:"LOW",estimatedMinutes:null}),hiddenBlock=await createTimeBlock(owner,{title:"Hidden linked",taskId:hiddenTask.id,date:"2026-10-07",startTime:"09:00",endTime:"10:00"}),deletedBlock=await createTimeBlock(owner,{title:"Deleted block",taskId:null,date:"2026-10-07",startTime:"10:00",endTime:"11:00"}),activeBlock=await createTimeBlock(owner,{title:"Overlap block",taskId:null,date:"2026-10-08",startTime:"09:00",endTime:"11:00"}),deletedEvent=await createEvent(owner,{title:"Deleted event",date:"2026-10-07",startTime:"11:00",endTime:"12:00",location:null,notes:null,recurring:false,interval:1,daysOfWeek:[],until:""}),activeEvent=await createEvent(owner,{title:"Overlap event",date:"2026-10-08",startTime:"09:30",endTime:"10:30",location:null,notes:null,recurring:false,interval:1,daysOfWeek:[],until:""});await createEvent(other,{title:"Foreign",date:"2026-10-08",startTime:"12:00",endTime:"13:00",location:null,notes:null,recurring:false,interval:1,daysOfWeek:[],until:""});await db.task.update({where:{id:hiddenTask.id},data:{deletedAt:new Date()}});await db.timeBlock.update({where:{id:deletedBlock.id},data:{deletedAt:new Date()}});await db.event.update({where:{id:deletedEvent.id},data:{deletedAt:new Date()}});const items=await getCalendarItemsForRange(owner,start,end),ids=new Set(items.map(item=>item.sourceId));expect(ids.has(hiddenTask.id)).toBe(false);expect(ids.has(hiddenBlock.id)).toBe(false);expect(ids.has(deletedBlock.id)).toBe(false);expect(ids.has(deletedEvent.id)).toBe(false);expect(ids.has(activeBlock.id)).toBe(true);expect(ids.has(activeEvent.id)).toBe(true);expect(items.some(item=>item.title==="Foreign")).toBe(false)});
});
