import "dotenv/config";
import { randomUUID } from "node:crypto";
import { afterAll, afterEach, beforeAll, describe, expect, it } from "vitest";
import { db } from "@/lib/db/client";
import { reflectionSchema, reviewItemInputSchema, type ReviewItemInput } from "@/lib/validation/daily-review";
import { getDailyReviewDetail, getDailyReviewHistory } from "@/server/queries/daily-review-queries";
import { jakartaDate } from "@/lib/date/jakarta";
import { DailyReviewRuleError, getDailyReviewSummary, nextReviewDate, reviewDateValue, submitDailyReview } from "./daily-review-service";

const token=randomUUID();let owner:string,other:string;const date="2026-09-29",today=reviewDateValue(date),tomorrow=reviewDateValue("2026-09-30");
const task=(userId:string,title:string,data:Record<string,unknown>={})=>db.task.create({data:{userId,title,...data}});
describe("Daily Review",()=>{
  beforeAll(async()=>{const users=await Promise.all(["owner","other"].map(name=>db.user.create({data:{username:`review-${name}-${token}`,passwordHash:"$argon2id$test"}})));owner=users[0].id;other=users[1].id});
  afterEach(async()=>{await db.dailyReview.deleteMany({where:{userId:{in:[owner,other]}}});await db.timeBlock.deleteMany({where:{userId:{in:[owner,other]}}});await db.task.deleteMany({where:{userId:{in:[owner,other]}}})});
  afterAll(async()=>{await db.user.deleteMany({where:{id:{in:[owner,other]}}})});

  it("uses Jakarta calendar boundaries for review and tomorrow dates",()=>{expect(jakartaDate(new Date("2026-09-28T17:00:00Z"))).toBe("2026-09-29");expect(jakartaDate(new Date("2026-09-29T16:59:59Z"))).toBe("2026-09-29");expect(jakartaDate(new Date("2026-09-29T17:00:00Z"))).toBe("2026-09-30");expect(nextReviewDate("2026-01-31")).toBe("2026-02-01");expect(nextReviewDate("2026-12-31")).toBe("2027-01-01");expect(reviewDateValue("2026-09-29").toISOString()).toBe("2026-09-29T00:00:00.000Z")});
  it("classifies completedAt and exact unfinished criteria without duplicates",async()=>{
    const completedToday=await task(owner,"Completed today",{status:"DONE",completedAt:new Date("2026-09-29T00:30:00+07:00")});
    await task(owner,"Completed yesterday",{status:"DONE",completedAt:new Date("2026-09-28T23:59:00+07:00")});
    const scheduled=await task(owner,"Scheduled"),pinned=await task(owner,"Pinned",{pinnedDate:today}),due=await task(owner,"Due",{deadlineAt:new Date("2026-09-29T23:59:00+07:00")}),triple=await task(owner,"Triple",{pinnedDate:today,deadlineAt:new Date("2026-09-29T12:00:00+07:00")});
    await task(owner,"Overdue only",{deadlineAt:new Date("2026-09-28T23:59:00+07:00")});
    await task(owner,"Deleted",{pinnedDate:today,deletedAt:new Date()});
    await task(owner,"Done eligible",{status:"DONE",pinnedDate:today,completedAt:new Date("2026-09-28T12:00:00+07:00")});
    await task(other,"Foreign",{pinnedDate:today});
    await db.timeBlock.createMany({data:[{userId:owner,taskId:scheduled.id,title:"Today",startAt:new Date("2026-09-29T09:00:00+07:00"),endAt:new Date("2026-09-29T10:00:00+07:00")},{userId:owner,taskId:triple.id,title:"Triple",startAt:new Date("2026-09-29T11:00:00+07:00"),endAt:new Date("2026-09-29T12:00:00+07:00")}]});
    const result=await getDailyReviewSummary(owner,date);expect(result.completed.map(t=>t.id)).toEqual([completedToday.id]);expect(result.unfinished.map(t=>t.id).sort()).toEqual([scheduled.id,pinned.id,due.id,triple.id].sort());expect(result.unfinished.filter(t=>t.id===triple.id)).toHaveLength(1);expect(result.unfinished.find(t=>t.id===triple.id)?.reasons).toEqual(["Scheduled","Pinned","Due today"]);
  });
  it("atomically applies mixed actions, snapshots titles, and safely deduplicates repeat submission",async()=>{
    await task(owner,"Completed",{status:"DONE",completedAt:new Date("2026-09-29T08:00:00+07:00")});
    const a=await task(owner,"Move tomorrow",{pinnedDate:today,priority:"HIGH",deadlineAt:new Date("2026-10-02T12:00Z")}),b=await task(owner,"Schedule later",{pinnedDate:today,deadlineAt:new Date("2026-10-03T12:00Z")}),c=await task(owner,"Keep me",{pinnedDate:today});
    const original={priority:a.priority,status:a.status,deadlineAt:a.deadlineAt};
    const inputs:ReviewItemInput[]=[{taskId:a.id,action:"TOMORROW"},{taskId:b.id,action:"RESCHEDULE",date:"2026-09-30",startTime:"19:00",endTime:"21:00"},{taskId:c.id,action:"KEEP"}];
    const review=await submitDailyReview(owner,date,"Hari ini cukup produktif.",inputs),again=await submitDailyReview(owner,date,"ignored",inputs);expect(again.id).toBe(review.id);expect(await db.dailyReview.count({where:{userId:owner,reviewDate:today}})).toBe(1);
    const moved=await db.task.findUniqueOrThrow({where:{id:a.id}});expect(moved).toMatchObject(original);expect(moved.pinnedDate?.toISOString()).toBe(tomorrow.toISOString());
    const block=await db.timeBlock.findFirstOrThrow({where:{taskId:b.id}});expect([block.startAt.toISOString(),block.endAt.toISOString()]).toEqual(["2026-09-30T12:00:00.000Z","2026-09-30T14:00:00.000Z"]);const rescheduled=await db.task.findUniqueOrThrow({where:{id:b.id}});expect(rescheduled.pinnedDate?.toISOString()).toBe(today.toISOString());expect(rescheduled.deadlineAt?.toISOString()).toBe("2026-10-03T12:00:00.000Z");expect(await db.timeBlock.count({where:{taskId:a.id}})).toBe(0);expect(await db.timeBlock.count({where:{taskId:c.id}})).toBe(0);expect((await db.task.findUniqueOrThrow({where:{id:c.id}})).pinnedDate?.toISOString()).toBe(today.toISOString());
    await db.task.update({where:{id:c.id},data:{title:"Renamed later"}});const detail=await getDailyReviewDetail(owner,review.id);expect(detail).toMatchObject({reflection:"Hari ini cukup produktif.",completedTaskCount:1,unfinishedTaskCount:3});expect(detail?.items.map(i=>[i.taskTitleSnapshot,i.action]).sort((x,y)=>x[0].localeCompare(y[0]))).toEqual([["Keep me","KEEP"],["Move tomorrow","TOMORROW"],["Schedule later","RESCHEDULE"]]);
  });
  it("rolls back all work when one reschedule is invalid",async()=>{const a=await task(owner,"A",{pinnedDate:today}),b=await task(owner,"B",{pinnedDate:today});await expect(submitDailyReview(owner,date,null,[{taskId:a.id,action:"TOMORROW"},{taskId:b.id,action:"RESCHEDULE",date:"2026-09-30",startTime:"21:00",endTime:"20:00"}])).rejects.toBeInstanceOf(DailyReviewRuleError);expect((await db.task.findUniqueOrThrow({where:{id:a.id}})).pinnedDate?.toISOString()).toBe(today.toISOString());expect(await db.dailyReview.count({where:{userId:owner}})).toBe(0);expect(await db.timeBlock.count({where:{userId:owner}})).toBe(0)});
  it("allows overlapping review blocks and preserves old blocks",async()=>{const taskA=await task(owner,"Overlap",{pinnedDate:today});await db.timeBlock.create({data:{userId:owner,taskId:taskA.id,title:"Old",startAt:new Date("2026-09-30T19:00:00+07:00"),endAt:new Date("2026-09-30T20:00:00+07:00")}});await submitDailyReview(owner,date,null,[{taskId:taskA.id,action:"RESCHEDULE",date:"2026-09-30",startTime:"19:30",endTime:"20:30"}]);expect(await db.timeBlock.count({where:{taskId:taskA.id}})).toBe(2);expect((await db.task.findUniqueOrThrow({where:{id:taskA.id}})).deadlineAt).toBeNull()});
  it("normalizes reflection and rejects incomplete reschedule input",()=>{expect(reflectionSchema.parse("   ")).toBeNull();expect(reflectionSchema.parse("  Fokus baik. ")).toBe("Fokus baik.");expect(reviewItemInputSchema.safeParse({taskId:randomUUID(),action:"RESCHEDULE",date:"2026-09-30",startTime:"20:00",endTime:"20:00"}).success).toBe(false)});
  it("rejects stale done/deleted tasks without partial mutation",async()=>{const done=await task(owner,"Done stale",{pinnedDate:today}),deleted=await task(owner,"Deleted stale",{pinnedDate:today}),active=await task(owner,"Active",{pinnedDate:today});await getDailyReviewSummary(owner,date);await db.task.update({where:{id:done.id},data:{status:"DONE",completedAt:new Date("2026-09-29T12:00:00+07:00")}});await db.task.update({where:{id:deleted.id},data:{deletedAt:new Date()}});await expect(submitDailyReview(owner,date,null,[{taskId:done.id,action:"TOMORROW"},{taskId:deleted.id,action:"KEEP"},{taskId:active.id,action:"TOMORROW"}])).rejects.toBeInstanceOf(DailyReviewRuleError);expect((await db.task.findUniqueOrThrow({where:{id:active.id}})).pinnedDate?.toISOString()).toBe(today.toISOString());expect(await db.dailyReview.count({where:{userId:owner}})).toBe(0)});
  it("cannot apply an action to another user's task",async()=>{const own=await task(owner,"Owned",{pinnedDate:today}),foreign=await task(other,"Foreign",{pinnedDate:today});await expect(submitDailyReview(owner,date,null,[{taskId:own.id,action:"KEEP"},{taskId:foreign.id,action:"TOMORROW"}])).rejects.toBeInstanceOf(DailyReviewRuleError);expect((await db.task.findUniqueOrThrow({where:{id:foreign.id}})).pinnedDate?.toISOString()).toBe(today.toISOString());expect(await db.dailyReview.count({where:{userId:owner}})).toBe(0)});
  it("orders owned history newest-first and hides another user's detail",async()=>{for(const day of ["2026-09-27","2026-09-29","2026-09-28"])await db.dailyReview.create({data:{userId:owner,reviewDate:reviewDateValue(day)}});const foreign=await db.dailyReview.create({data:{userId:other,reviewDate:today}});expect((await getDailyReviewHistory(owner)).map(r=>r.reviewDate.toISOString().slice(0,10))).toEqual(["2026-09-29","2026-09-28","2026-09-27"]);expect(await getDailyReviewDetail(owner,foreign.id)).toBeNull()});
});
