import "dotenv/config";
import { randomUUID } from "node:crypto";
import { afterAll, beforeAll, describe, expect, it } from "vitest";
import { db } from "@/lib/db/client";
import { eventInputSchema, type EventInput } from "@/lib/validation/event";
import { getEventOccurrencesForRange } from "@/server/queries/event-queries";
import { createEvent, deleteEvent, eventTemporalState, updateEvent } from "./event-service";

const token=randomUUID();let owner:string,other:string;const input=(overrides:Partial<EventInput>={}):EventInput=>({title:"Kuliah",date:"2026-10-05",startTime:"08:00",endTime:"09:40",location:null,notes:null,recurring:false,interval:1,daysOfWeek:[],until:"",...overrides});
describe("events and recurrence",()=>{
  beforeAll(async()=>{const users=await Promise.all(["owner","other"].map(name=>db.user.create({data:{username:`event-${name}-${token}`,passwordHash:"$argon2id$test"}})));owner=users[0].id;other=users[1].id});
  afterAll(async()=>{const rules=(await db.event.findMany({where:{userId:{in:[owner,other]},recurrenceRuleId:{not:null}},select:{recurrenceRuleId:true}})).flatMap(event=>event.recurrenceRuleId?[event.recurrenceRuleId]:[]);await db.event.deleteMany({where:{userId:{in:[owner,other]}}});await db.recurrenceRule.deleteMany({where:{id:{in:rules}}});await db.user.deleteMany({where:{id:{in:[owner,other]}}})});
  it("creates one-time events with Jakarta semantics and normalized optional fields",async()=>{const parsed=eventInputSchema.parse({...input(),title:"  Rapat  ",location:"",notes:""}),event=await createEvent(owner,parsed);expect(event).toMatchObject({userId:owner,title:"Rapat",location:null,notes:null,recurrenceRule:null});expect(event.startAt.toISOString()).toBe("2026-10-05T01:00:00.000Z");expect(event.endAt.toISOString()).toBe("2026-10-05T02:40:00.000Z")});
  it("validates time, weekday, interval, and until on the server schema",()=>{const raw=(overrides:Record<string,unknown>={})=>({...input(),location:"",notes:"",...overrides});expect(eventInputSchema.safeParse(raw()).success).toBe(true);expect(eventInputSchema.safeParse(raw({endTime:"08:00"})).success).toBe(false);expect(eventInputSchema.safeParse(raw({endTime:"07:00"})).success).toBe(false);expect(eventInputSchema.safeParse(raw({recurring:true,daysOfWeek:[]})).success).toBe(false);expect(eventInputSchema.safeParse(raw({recurring:true,daysOfWeek:["MONDAY"],interval:0})).success).toBe(false);expect(eventInputSchema.safeParse(raw({recurring:true,daysOfWeek:["MONDAY"],until:"2026-10-04"})).success).toBe(false)});
  it("expands multiple weekdays, preserves wall clock and duration, and bounds the range",async()=>{const event=await createEvent(owner,input({title:"Class",recurring:true,daysOfWeek:["MONDAY","WEDNESDAY"]}));const found=(await getEventOccurrencesForRange(owner,new Date("2026-10-05T00:00:00+07:00"),new Date("2026-10-12T00:00:00+07:00"))).filter(item=>item.eventId===event.id);expect(found).toHaveLength(2);expect(found.map(item=>item.startAt.toISOString())).toEqual(["2026-10-05T01:00:00.000Z","2026-10-07T01:00:00.000Z"]);expect(found.every(item=>item.endAt.getTime()-item.startAt.getTime()===100*60_000)).toBe(true);expect(found.every(item=>item.id.startsWith(`${event.id}:`))).toBe(true)});
  it("supports interval two and an inclusive until boundary",async()=>{const event=await createEvent(owner,input({title:"Biweekly",recurring:true,interval:2,daysOfWeek:["MONDAY"],until:"2026-11-02"}));const found=(await getEventOccurrencesForRange(owner,new Date("2026-10-01T00:00:00+07:00"),new Date("2026-11-10T00:00:00+07:00"))).filter(item=>item.eventId===event.id);expect(found.map(item=>new Date(item.startAt.getTime()+25_200_000).toISOString().slice(0,10))).toEqual(["2026-10-05","2026-10-19","2026-11-02"])});
  it("keeps dates near Jakarta day boundaries",async()=>{const early=await createEvent(owner,input({title:"Early",date:"2026-10-06",startTime:"00:30",endTime:"01:30",recurring:true,daysOfWeek:["TUESDAY"]}));const late=await createEvent(owner,input({title:"Late",date:"2026-10-06",startTime:"23:30",endTime:"23:59",recurring:true,daysOfWeek:["TUESDAY"]}));const found=await getEventOccurrencesForRange(owner,new Date("2026-10-06T00:00:00+07:00"),new Date("2026-10-07T00:00:00+07:00"));expect(found.find(item=>item.eventId===early.id)?.startAt.toISOString()).toBe("2026-10-05T17:30:00.000Z");expect(found.find(item=>item.eventId===late.id)?.startAt.toISOString()).toBe("2026-10-06T16:30:00.000Z")});
  it("edits one-time events without creating recurrence",async()=>{const event=await createEvent(owner,input({title:"One"}));const updated=await updateEvent(owner,event.id,input({title:"Edited",startTime:"10:00",endTime:"11:00",location:"Lab",notes:"Laptop"}));expect(updated).toMatchObject({title:"Edited",location:"Lab",notes:"Laptop",recurrenceRule:null});expect(updated?.startAt.toISOString()).toBe("2026-10-05T03:00:00.000Z")});
  it("edits and deletes an entire derived series while preserving one-time events",async()=>{const one=await createEvent(owner,input({title:"Keep"})),series=await createEvent(owner,input({title:"Old",recurring:true,daysOfWeek:["MONDAY"]}));await updateEvent(owner,series.id,input({title:"New",startTime:"12:00",endTime:"13:00",recurring:true,daysOfWeek:["WEDNESDAY"]}));let found=await getEventOccurrencesForRange(owner,new Date("2026-10-05T00:00:00+07:00"),new Date("2026-10-12T00:00:00+07:00"));expect(found.filter(item=>item.eventId===series.id).map(item=>[item.title,item.startAt.toISOString()])).toEqual([["New","2026-10-07T05:00:00.000Z"]]);expect(await deleteEvent(owner,series.id)).toBe(true);found=await getEventOccurrencesForRange(owner,new Date("2026-10-05T00:00:00+07:00"),new Date("2026-10-12T00:00:00+07:00"));expect(found.some(item=>item.eventId===series.id)).toBe(false);expect(found.some(item=>item.eventId===one.id)).toBe(true)});
  it("isolates ownership, orders unified results, and derives temporal state",async()=>{const foreign=await createEvent(other,input({title:"Foreign"}));expect(await updateEvent(owner,foreign.id,input({title:"Stolen"}))).toBeNull();expect(await deleteEvent(owner,foreign.id)).toBe(false);expect((await getEventOccurrencesForRange(owner,new Date("2026-10-05T00:00:00+07:00"),new Date("2026-10-06T00:00:00+07:00"))).some(item=>item.eventId===foreign.id)).toBe(false);const now=new Date("2026-10-05T02:00:00Z");expect(eventTemporalState({startAt:new Date("2026-10-05T00:00Z"),endAt:new Date("2026-10-05T01:00Z")},now)).toBe("past");expect(eventTemporalState({startAt:new Date("2026-10-05T01:00Z"),endAt:new Date("2026-10-05T03:00Z")},now)).toBe("current");expect(eventTemporalState({startAt:new Date("2026-10-05T03:00Z"),endAt:new Date("2026-10-05T04:00Z")},now)).toBe("future")});
});
