import "dotenv/config";
import { randomUUID } from "node:crypto";
import { afterAll,beforeAll,describe,expect,it } from "vitest";
import { db } from "@/lib/db/client";
import { jakartaDayRange } from "@/lib/date/jakarta";
import { rankSmartTasks } from "@/lib/smart-today/scoring";
import { parseTaskDiscovery } from "@/lib/validation/task-discovery";
import { getDailyReviewSummary,reviewDateValue } from "./daily-review-service";
import { deleteProject } from "./project-service";
import { deleteTask,permanentlyDeleteTask,restoreTask,taskProgress } from "./task-service";
import { getFilteredTasks,getTrashedTasks } from "@/server/queries/task-queries";
import { getTimeBlocksForRange } from "@/server/queries/time-block-queries";
import { getCalendarItemsForRange } from "@/server/queries/calendar-queries";
import { getSmartTodayTasks } from "@/server/queries/today-queries";
import { getProjectProgress } from "./project-service";

const token=randomUUID(),date="2026-09-29",now=new Date("2026-09-29T05:00:00Z"),range=jakartaDayRange(date);let owner:string,other:string,areaA:string,areaB:string,projectA:string,projectB:string;const ids:Record<string,string>={};
const filters=(overrides:Record<string,string|string[]|undefined>={})=>parseTaskDiscovery(overrides);
describe("task discovery and trash",()=>{
  beforeAll(async()=>{const users=await Promise.all(["owner","other"].map(name=>db.user.create({data:{username:`discovery-${name}-${token}`,passwordHash:"$argon2id$test"}})));owner=users[0].id;other=users[1].id;const areas=await Promise.all([db.area.create({data:{userId:owner,name:"Kuliah"}}),db.area.create({data:{userId:owner,name:"Personal"}})]);areaA=areas[0].id;areaB=areas[1].id;const projects=await Promise.all([db.project.create({data:{userId:owner,areaId:areaA,name:"Project A"}}),db.project.create({data:{userId:owner,areaId:areaB,name:"Project B"}})]);projectA=projects[0].id;projectB=projects[1].id;const tasks=await Promise.all([
    db.task.create({data:{userId:owner,projectId:projectA,title:"Kerjakan Laporan ML",description:"not searchable secret",status:"TODO",priority:"HIGH",deadlineAt:new Date("2026-09-29T18:00:00+07:00"),createdAt:new Date("2026-09-20Z")}}),
    db.task.create({data:{userId:owner,projectId:projectA,title:"LAPORAN TOEFL",status:"IN_PROGRESS",priority:"URGENT",deadlineAt:new Date("2026-09-30T09:00:00+07:00"),pinnedDate:reviewDateValue(date),createdAt:new Date("2026-09-22Z")}}),
    db.task.create({data:{userId:owner,projectId:projectB,title:"Belajar Big Data",status:"DONE",priority:"LOW",deadlineAt:new Date("2026-09-28T10:00:00+07:00"),completedAt:new Date("2026-09-28Z"),createdAt:new Date("2026-09-24Z")}}),
    db.task.create({data:{userId:owner,title:"Tanpa Deadline",status:"TODO",priority:"MEDIUM",createdAt:new Date("2026-09-26Z")}}),
    db.task.create({data:{userId:owner,title:"Laporan Deleted",deletedAt:new Date(),priority:"URGENT"}}),
    db.task.create({data:{userId:other,title:"Kerjakan Laporan Foreign",priority:"URGENT"}}),
  ]);[ids.ml,ids.toefl,ids.big,ids.none,ids.deleted,ids.foreign]=tasks.map(t=>t.id);await db.subtask.createMany({data:[{taskId:ids.ml,title:"one",isCompleted:true},{taskId:ids.ml,title:"two"}]});await db.timeBlock.create({data:{userId:owner,taskId:ids.none,title:"Scheduled",startAt:new Date("2026-09-29T09:00:00+07:00"),endAt:new Date("2026-09-29T10:00:00+07:00")}})},30000);
  afterAll(async()=>{const users=await db.user.findMany({where:{username:{startsWith:"discovery-",endsWith:token}},select:{id:true}}),userIds=users.map(user=>user.id);if(userIds.length){await db.dailyReview.deleteMany({where:{userId:{in:userIds}}});await db.timeBlock.deleteMany({where:{userId:{in:userIds}}});await db.task.deleteMany({where:{userId:{in:userIds}}});await db.project.deleteMany({where:{userId:{in:userIds}}});await db.area.deleteMany({where:{userId:{in:userIds}}});await db.user.deleteMany({where:{id:{in:userIds}}})}await db.$disconnect()},30000);
  it("searches title only with case-insensitive partial matching, normalizes whitespace, and excludes deleted/foreign tasks",async()=>{expect((await getFilteredTasks(owner,filters({q:"  kerjakan   laporan  "}),now,date)).map(t=>t.id)).toEqual([ids.ml]);expect((await getFilteredTasks(owner,filters({q:"SECRET"}),now,date))).toHaveLength(0);expect((await getFilteredTasks(owner,filters({q:"   "}),now,date))).toHaveLength(4)});
  it("validates params and combines OR within groups with AND across groups",async()=>{const parsed=filters({status:["TODO","IN_PROGRESS","BAD"],priority:"HIGH,URGENT",project:"not-a-uuid",sort:"nonsense"});expect(parsed).toMatchObject({statuses:["TODO","IN_PROGRESS"],priorities:["HIGH","URGENT"],projectId:null,sort:"DEFAULT"});expect((await getFilteredTasks(owner,parsed,now,date)).map(t=>t.id).sort()).toEqual([ids.ml,ids.toefl].sort());expect((await getFilteredTasks(owner,filters({status:"IN_PROGRESS",priority:"URGENT",area:areaA,q:"toefl"}),now,date)).map(t=>t.id)).toEqual([ids.toefl])});
  it("filters owned Project and derived Area without matching unassigned or foreign values",async()=>{expect((await getFilteredTasks(owner,filters({project:projectA}),now,date)).map(t=>t.id).sort()).toEqual([ids.ml,ids.toefl].sort());expect((await getFilteredTasks(owner,filters({area:areaB}),now,date)).map(t=>t.id)).toEqual([ids.big]);const foreignProject=await db.project.create({data:{userId:other,name:"Foreign"}});expect(await getFilteredTasks(owner,filters({project:foreignProject.id}),now,date)).toHaveLength(0)});
  it("applies Jakarta deadline categories and intersects status with overdue",async()=>{expect((await getFilteredTasks(owner,filters({deadline:"TODAY"}),now,date)).map(t=>t.id)).toEqual([ids.ml]);expect((await getFilteredTasks(owner,filters({deadline:"UPCOMING"}),now,date)).map(t=>t.id)).toEqual([ids.toefl]);expect(await getFilteredTasks(owner,filters({deadline:"OVERDUE"}),now,date)).toHaveLength(0);expect((await getFilteredTasks(owner,filters({deadline:"NONE"}),now,date)).map(t=>t.id)).toEqual([ids.none]);const overdue=await db.task.create({data:{userId:owner,title:"Overdue TODO",status:"TODO",deadlineAt:new Date("2026-09-28T10:00:00+07:00")}});expect((await getFilteredTasks(owner,filters({deadline:"OVERDUE",status:"TODO"}),now,date)).map(task=>task.id)).toEqual([overdue.id]);expect(await getFilteredTasks(owner,filters({deadline:"OVERDUE",status:"IN_PROGRESS"}),now,date)).toHaveLength(0);await db.task.delete({where:{id:overdue.id}})});
  it("sorts deadline null-last, priority exact, and created newest-first deterministically",async()=>{expect((await getFilteredTasks(owner,filters({sort:"deadline"}),now,date)).map(t=>t.id)).toEqual([ids.big,ids.ml,ids.toefl,ids.none]);expect((await getFilteredTasks(owner,filters({sort:"priority"}),now,date)).map(t=>t.id)).toEqual([ids.toefl,ids.ml,ids.none,ids.big]);expect((await getFilteredTasks(owner,filters({sort:"created"}),now,date)).map(t=>t.id)).toEqual([ids.none,ids.big,ids.toefl,ids.ml])});
  it("sorts every result with the exact reusable Phase 8 Smart comparator",async()=>{const all=await getFilteredTasks(owner,filters(),now,date),expected=rankSmartTasks(all.map(task=>({...task,progress:taskProgress(task).progress,scheduledToday:task.timeBlocks.length>0})),now,date).map(t=>t.id),smart=await getFilteredTasks(owner,filters({sort:"smart"}),now,date);expect(smart.map(t=>t.id)).toEqual(expected);expect(smart).toHaveLength(4)});
  it("composes search, filters, and sort",async()=>{const result=await getFilteredTasks(owner,filters({q:"laporan",status:"TODO,IN_PROGRESS",priority:"HIGH,URGENT",area:areaA,sort:"priority"}),now,date);expect(result.map(t=>t.id)).toEqual([ids.toefl,ids.ml])});
  it("soft deletes from every active surface, preserves children, and restores the same relations",async()=>{const visibility=await db.task.create({data:{userId:owner,projectId:projectA,title:"Visibility Restore",priority:"HIGH",pinnedDate:reviewDateValue(date),deadlineAt:new Date("2026-09-29T20:00:00+07:00")}}),sub=await db.subtask.create({data:{taskId:visibility.id,title:"Keep"}}),block=await db.timeBlock.create({data:{userId:owner,taskId:visibility.id,title:"Visibility block",startAt:new Date("2026-09-29T13:00:00+07:00"),endAt:new Date("2026-09-29T14:00:00+07:00")}}),before=await getProjectProgress(owner,projectA);expect(await deleteTask(owner,visibility.id)).toBe(true);expect((await getTrashedTasks(owner)).some(t=>t.id===visibility.id)).toBe(true);expect((await getFilteredTasks(owner,filters({q:"Visibility"}),now,date))).toHaveLength(0);expect((await getTimeBlocksForRange(owner,range.start,range.end)).some(b=>b.id===block.id)).toBe(false);expect((await getCalendarItemsForRange(owner,range.start,range.end)).some(item=>item.sourceId===visibility.id||item.sourceId===block.id)).toBe(false);expect((await getSmartTodayTasks(owner,now,range.start,range.end,date)).some(t=>t.id===visibility.id)).toBe(false);expect((await getDailyReviewSummary(owner,date)).unfinished.some(t=>t.id===visibility.id)).toBe(false);expect((await getProjectProgress(owner,projectA)).totalTasks).toBe(before.totalTasks-1);expect(await db.subtask.findUnique({where:{id:sub.id}})).not.toBeNull();expect(await db.timeBlock.findUnique({where:{id:block.id}})).not.toBeNull();expect(await restoreTask(owner,visibility.id)).toBe(true);expect((await getTimeBlocksForRange(owner,range.start,range.end)).filter(b=>b.id===block.id)).toHaveLength(1);expect((await db.task.findUniqueOrThrow({where:{id:visibility.id}})).projectId).toBe(projectA);expect((await getProjectProgress(owner,projectA)).totalTasks).toBe(before.totalTasks)});
  it("keeps valid Project on restore and never relinks one removed by Project deletion",async()=>{const valid=await db.task.create({data:{userId:owner,projectId:projectA,title:"Restore valid",deletedAt:new Date()}});await restoreTask(owner,valid.id);expect((await db.task.findUniqueOrThrow({where:{id:valid.id}})).projectId).toBe(projectA);const removedProject=await db.project.create({data:{userId:owner,name:"Delete project"}}),detached=await db.task.create({data:{userId:owner,projectId:removedProject.id,title:"Detached",deletedAt:new Date()}});await deleteProject(owner,removedProject.id);await restoreTask(owner,detached.id);expect((await db.task.findUniqueOrThrow({where:{id:detached.id}})).projectId).toBeNull()});
  it("permanently deletes only trashed owned tasks, cascades children, and preserves review snapshot",async()=>{const active=await db.task.create({data:{userId:owner,title:"Active cannot purge"}});expect(await permanentlyDeleteTask(owner,active.id)).toBe(false);const doomed=await db.task.create({data:{userId:owner,title:"Historical title",deletedAt:new Date()}}),sub=await db.subtask.create({data:{taskId:doomed.id,title:"Child"}}),block=await db.timeBlock.create({data:{userId:owner,taskId:doomed.id,title:"Child block",startAt:range.start,endAt:new Date(range.start.getTime()+3600000)}}),review=await db.dailyReview.create({data:{userId:owner,reviewDate:reviewDateValue("2026-09-28"),items:{create:{taskId:doomed.id,taskTitleSnapshot:"Historical title",action:"KEEP"}}},include:{items:true}});expect(await permanentlyDeleteTask(other,doomed.id)).toBe(false);expect(await permanentlyDeleteTask(owner,doomed.id)).toBe(true);expect(await db.task.findUnique({where:{id:doomed.id}})).toBeNull();expect(await db.subtask.findUnique({where:{id:sub.id}})).toBeNull();expect(await db.timeBlock.findUnique({where:{id:block.id}})).toBeNull();const item=await db.dailyReviewItem.findUniqueOrThrow({where:{id:review.items[0].id}});expect(item).toMatchObject({taskId:null,taskTitleSnapshot:"Historical title"});expect(await db.dailyReview.findUnique({where:{id:review.id}})).not.toBeNull()});
  it("blocks cross-user restore",async()=>{const trashed=await db.task.create({data:{userId:owner,title:"Owned trash",deletedAt:new Date()}});expect(await restoreTask(other,trashed.id)).toBe(false);expect((await db.task.findUniqueOrThrow({where:{id:trashed.id}})).deletedAt).not.toBeNull()});
});
