import "dotenv/config";import{randomUUID}from"node:crypto";import{afterAll,beforeAll,describe,expect,it}from"vitest";import{db}from"@/lib/db/client";import{taskInputSchema}from"@/lib/validation/task";import{getTaskByIdForUser,getTasksForUser}from"@/server/queries/task-queries";import{changeProjectStatus,createProject,getProjectProgress}from"./project-service";import{changeTaskStatus,createSubtask,createTask,deadlineFromInput,deleteSubtask,deleteTask,isTaskOverdue,taskProgress,TaskRuleError,toggleSubtask,updateSubtask,updateTask}from"./task-service";
const x=randomUUID();let a:string,b:string,project:string,task:string;const input=(projectId:string|null=project)=>({title:"Task test",description:null,projectId,deadlineDate:"",deadlineTime:"",priority:"MEDIUM" as const,estimatedMinutes:null});
beforeAll(async()=>{const users=await Promise.all([db.user.create({data:{username:`task-a-${x}`,passwordHash:"$argon2id$test"}}),db.user.create({data:{username:`task-b-${x}`,passwordHash:"$argon2id$test"}})]);a=users[0].id;b=users[1].id;project=(await createProject(a,{name:"P",description:null,icon:null,areaId:null,startDate:"",targetDate:""})).id;task=(await createTask(a,input())).id});
afterAll(async()=>{await db.subtask.deleteMany({where:{task:{userId:{in:[a,b]}}}});await db.task.deleteMany({where:{userId:{in:[a,b]}}});await db.project.deleteMany({where:{userId:{in:[a,b]}}});await db.user.deleteMany({where:{id:{in:[a,b]}}});await db.$disconnect()});
describe("task and subtask rules",()=>{
it("creates defaults and optional fields",async()=>{const t=await db.task.findUniqueOrThrow({where:{id:task}});expect(t).toMatchObject({userId:a,status:"TODO",priority:"MEDIUM",description:null})});
it("rejects invalid title, duration, and foreign or deleted projects",async()=>{expect(taskInputSchema.safeParse({...input(null),title:" ",estimatedMinutes:"0"}).success).toBe(false);const foreign=await createProject(b,{name:"Foreign",description:null,icon:null,areaId:null,startDate:"",targetDate:""});await expect(createTask(a,input(foreign.id))).rejects.toBeInstanceOf(TaskRuleError);await db.project.update({where:{id:foreign.id},data:{deletedAt:new Date()}});await expect(createTask(a,input(foreign.id))).rejects.toBeInstanceOf(TaskRuleError)});
it("stores date-only deadlines at 23:59 Jakarta and derives overdue",()=>{const d=deadlineFromInput("2026-09-30","");expect(d?.toISOString()).toBe("2026-09-30T16:59:00.000Z");expect(isTaskOverdue({deadlineAt:d,status:"TODO",deletedAt:null},new Date("2026-10-01T00:00:00Z"))).toBe(true);expect(isTaskOverdue({deadlineAt:d,status:"DONE",deletedAt:null},new Date("2026-10-01T00:00:00Z"))).toBe(false);expect(isTaskOverdue({deadlineAt:null,status:"TODO",deletedAt:null})).toBe(false)});
it("handles progress boundaries and DONE checklist semantics",()=>{expect(taskProgress({status:"TODO",subtasks:[]} ).progress).toBe(0);expect(taskProgress({status:"DONE",subtasks:[]} ).progress).toBe(100);for(const done of[1,2,3,4])expect(taskProgress({status:"DONE",subtasks:Array.from({length:4},(_,i)=>({isCompleted:i<done}))}).progress).toBe(done*25)});
it("creates ordered subtasks, edits, toggles, and never auto-completes task",async()=>{const subs=[];for(const title of["A","B","C","D"])subs.push(await createSubtask(a,task,title));expect(subs.map(s=>s?.position)).toEqual([0,1,2,3]);expect(await updateSubtask(a,subs[0]!.id,"Edited")).toBe(true);for(const s of subs)await toggleSubtask(a,s!.id);expect((await db.task.findUniqueOrThrow({where:{id:task}})).status).toBe("TODO");await toggleSubtask(a,subs[0]!.id);expect((await db.subtask.findUniqueOrThrow({where:{id:subs[0]!.id}})).completedAt).toBeNull();expect(await deleteSubtask(a,subs[3]!.id)).toBe(true)});
it("enforces transitions and preserves subtasks on reopen",async()=>{await changeTaskStatus(a,task,"IN_PROGRESS");await changeTaskStatus(a,task,"DONE");expect((await db.task.findUniqueOrThrow({where:{id:task}})).completedAt).not.toBeNull();await changeTaskStatus(a,task,"TODO");expect((await db.task.findUniqueOrThrow({where:{id:task}})).completedAt).toBeNull();expect(await db.subtask.count({where:{taskId:task}})).toBe(3)});
it("blocks all cross-user task and subtask operations",async()=>{const s=await db.subtask.findFirstOrThrow({where:{taskId:task}});expect(await getTaskByIdForUser(b,task)).toBeNull();expect(await updateTask(b,task,input(null))).toBe(false);expect(await changeTaskStatus(b,task,"DONE")).toBe(false);expect(await deleteTask(b,task)).toBe(false);expect(await createSubtask(b,task,"x")).toBeNull();expect(await updateSubtask(b,s.id,"x")).toBe(false);expect(await toggleSubtask(b,s.id)).toBe(false);expect(await deleteSubtask(b,s.id)).toBe(false)});
it("updates project progress, completion guard, and soft delete exclusion",async()=>{await changeTaskStatus(a,task,"DONE");expect((await getProjectProgress(a,project)).progress).toBe(100);await changeTaskStatus(a,task,"TODO");await expect(changeProjectStatus(a,project,"COMPLETED")).rejects.toThrow();const count=await db.subtask.count({where:{taskId:task}});expect(await deleteTask(a,task)).toBe(true);expect((await getTasksForUser(a)).find(t=>t.id===task)).toBeUndefined();expect(await getTaskByIdForUser(a,task)).toBeNull();expect(await db.subtask.count({where:{taskId:task}})).toBe(count);expect((await getProjectProgress(a,project)).progress).toBe(0);await expect(changeProjectStatus(a,project,"COMPLETED")).resolves.toBe(true)});
});
