import"dotenv/config";import{randomUUID}from"node:crypto";import{afterAll,beforeAll,describe,expect,it}from"vitest";import{db}from"@/lib/db/client";import{getEligibleRescheduleBlocks,getTimeBlocksForDay}from"@/server/queries/time-block-queries";import{createTask}from"./task-service";import{createTimeBlock,deleteTimeBlock,dismissReschedule,findOverlaps,intervalsOverlap,rescheduleTimeBlock,temporalState,updateTimeBlock}from"./time-block-service";
const x=randomUUID();let a:string,b:string,task:string,foreignTask:string;const deadline=new Date("2026-10-15T16:59:00Z");const input=(date="2026-10-01",startTime="09:00",endTime="10:00",taskId:string|null=null,title="Block")=>({title,taskId,date,startTime,endTime});
beforeAll(async()=>{const[u1,u2]=await Promise.all([db.user.create({data:{username:`block-a-${x}`,passwordHash:"$argon2id$test"}}),db.user.create({data:{username:`block-b-${x}`,passwordHash:"$argon2id$test"}})]);a=u1.id;b=u2.id;task=(await createTask(a,{title:"Task",description:null,projectId:null,deadlineDate:"2026-10-15",deadlineTime:"23:59",priority:"MEDIUM",estimatedMinutes:null})).id;foreignTask=(await createTask(b,{title:"Foreign",description:null,projectId:null,deadlineDate:"",deadlineTime:"",priority:"MEDIUM",estimatedMinutes:null})).id});
afterAll(async()=>{const ids=[a,b].filter(Boolean);if(ids.length){await db.timeBlock.deleteMany({where:{userId:{in:ids}}});await db.task.deleteMany({where:{userId:{in:ids}}});await db.user.deleteMany({where:{id:{in:ids}}})}await db.$disconnect()});
const assertDeadline=async()=>expect((await db.task.findUniqueOrThrow({where:{id:task}})).deadlineAt?.toISOString()).toBe(deadline.toISOString());
describe("time blocks",()=>{
it("supports standalone, linked, and multiple blocks without changing deadline",async()=>{expect((await createTimeBlock(a,input())).taskId).toBeNull();const linked=await createTimeBlock(a,input("2026-10-01","10:00","11:00",task));expect(linked.taskId).toBe(task);expect((await createTimeBlock(a,input("2026-10-01","14:00","15:00",task))).taskId).toBe(task);expect(await db.timeBlock.count({where:{userId:a,taskId:task}})).toBeGreaterThanOrEqual(2);await assertDeadline();expect(await updateTimeBlock(a,linked.id,input("2026-10-01","11:00","12:00",task,"Updated"))).toBe(true);await assertDeadline();expect(await deleteTimeBlock(a,linked.id)).toBe(true);await assertDeadline()});
it("implements strict overlap boundaries and self exclusion",async()=>{const d=(h:string)=>new Date(`2026-10-02T${h}:00+07:00`),a1={startAt:d("09:00"),endAt:d("10:00")};expect(intervalsOverlap(a1,{startAt:d("09:30"),endAt:d("10:30")})).toBe(true);expect(intervalsOverlap({startAt:d("09:00"),endAt:d("12:00")},{startAt:d("10:00"),endAt:d("11:00")})).toBe(true);expect(intervalsOverlap(a1,{...a1})).toBe(true);expect(intervalsOverlap(a1,{startAt:d("10:00"),endAt:d("11:00")})).toBe(false);expect(intervalsOverlap(a1,{startAt:d("08:00"),endAt:d("09:00")})).toBe(false);const block=await createTimeBlock(a,input("2026-10-02","09:00","10:00"));expect(await findOverlaps(a,block.startAt,block.endAt,block.id)).toHaveLength(0)});
it("allows overlap saves and validates foreign/deleted tasks",async()=>{const one=await createTimeBlock(a,input("2026-10-03","09:00","10:00"));const two=await createTimeBlock(a,input("2026-10-03","09:30","10:30"));expect((await findOverlaps(a,two.startAt,two.endAt,two.id)).some(v=>v.id===one.id)).toBe(true);await expect(createTimeBlock(a,input("2026-10-03","11:00","12:00",foreignTask))).rejects.toThrow();await db.task.update({where:{id:foreignTask},data:{deletedAt:new Date()}});await expect(createTimeBlock(a,input("2026-10-03","12:00","13:00",foreignTask))).rejects.toThrow()});
it("derives temporal state",()=>{const now=new Date("2026-10-04T03:00:00Z");expect(temporalState({startAt:new Date("2026-10-04T01:00Z"),endAt:new Date("2026-10-04T02:00Z")},now)).toBe("past");expect(temporalState({startAt:new Date("2026-10-04T02:00Z"),endAt:new Date("2026-10-04T04:00Z")},now)).toBe("current");expect(temporalState({startAt:new Date("2026-10-04T04:00Z"),endAt:new Date("2026-10-04T05:00Z")},now)).toBe("future")});
it("returns only the most recent eligible block per unfinished task",async()=>{const old=await createTimeBlock(a,input("2026-09-20","09:00","10:00",task,"Old"));const recent=await createTimeBlock(a,input("2026-09-21","09:00","10:00",task,"Recent"));const eligible=await getEligibleRescheduleBlocks(a,new Date("2026-09-22T00:00:00Z"));expect(eligible.filter(v=>v.taskId===task).map(v=>v.id)).toEqual([recent.id]);await db.timeBlock.update({where:{id:old.id},data:{rescheduleState:"DISMISSED"}})});
it("reschedules atomically, preserves history, chains, and never changes task",async()=>{const old=await createTimeBlock(a,input("2026-09-23","09:00","10:00",task,"Chain")),oldTime=old.startAt;const next=await rescheduleTimeBlock(a,old.id,"2026-09-24","11:00","12:00");expect(await db.timeBlock.findUniqueOrThrow({where:{id:old.id}})).toMatchObject({rescheduleState:"RESCHEDULED",startAt:oldTime,deletedAt:null});expect(next).toMatchObject({taskId:task,rescheduledFromId:old.id,rescheduleState:"NONE"});const third=await rescheduleTimeBlock(a,next!.id,"2026-09-25","13:00","14:00");expect(third?.rescheduledFromId).toBe(next!.id);await assertDeadline();expect((await db.task.findUniqueOrThrow({where:{id:task}})).status).toBe("TODO")});
it("allows only one replacement when reschedule is submitted concurrently",async()=>{const old=await createTimeBlock(a,input("2026-09-18","09:00","10:00",task,"Concurrent"));const results=await Promise.all([rescheduleTimeBlock(a,old.id,"2026-09-19","11:00","12:00"),rescheduleTimeBlock(a,old.id,"2026-09-19","13:00","14:00")]);expect(results.filter(Boolean)).toHaveLength(1);expect(await db.timeBlock.count({where:{rescheduledFromId:old.id}})).toBe(1)});
it("dismisses without creating a block and preserves deadline",async()=>{const block=await createTimeBlock(a,input("2026-09-26","09:00","10:00",task));const before=await db.timeBlock.count({where:{userId:a}});expect(await dismissReschedule(a,block.id)).toBe(true);expect(await db.timeBlock.count({where:{userId:a}})).toBe(before);expect((await db.timeBlock.findUniqueOrThrow({where:{id:block.id}})).rescheduleState).toBe("DISMISSED");await assertDeadline()});
it("enforces ownership and hides blocks of trashed tasks while retaining DB rows",async()=>{const block=await createTimeBlock(a,input("2026-10-06","09:00","10:00",task));expect(await updateTimeBlock(b,block.id,input("2026-10-06","10:00","11:00"))).toBe(false);expect(await deleteTimeBlock(b,block.id)).toBe(false);expect(await dismissReschedule(b,block.id)).toBe(false);expect(await rescheduleTimeBlock(b,block.id,"2026-10-07","09:00","10:00")).toBeNull();await db.task.update({where:{id:task},data:{deletedAt:new Date()}});expect(await db.timeBlock.findUnique({where:{id:block.id}})).not.toBeNull();expect((await getTimeBlocksForDay(a,"2026-10-06")).some(v=>v.id===block.id)).toBe(false)});
});
