import { db } from "@/lib/db/client"; import { jakartaDateTime } from "@/lib/date/jakarta"; import type { TimeBlockInput } from "@/lib/validation/time-block";
export class TimeBlockRuleError extends Error {}
export function intervalsOverlap(a:{startAt:Date;endAt:Date},b:{startAt:Date;endAt:Date}){return a.startAt<b.endAt&&a.endAt>b.startAt}
export function temporalState(b:{startAt:Date;endAt:Date},now=new Date()){return b.endAt<=now?"past":b.startAt<=now&&now<b.endAt?"current":"future"}
async function taskAvailable(userId:string,taskId:string|null){return !taskId||Boolean(await db.task.findFirst({where:{id:taskId,userId,deletedAt:null},select:{id:true}}))}
function times(i:TimeBlockInput){return{startAt:jakartaDateTime(i.date,i.startTime),endAt:jakartaDateTime(i.date,i.endTime)}}
export async function findOverlaps(userId:string,startAt:Date,endAt:Date,excludeId?:string){const [blocks,events]=await Promise.all([db.timeBlock.findMany({where:{userId,deletedAt:null,id:excludeId?{not:excludeId}:undefined,startAt:{lt:endAt},endAt:{gt:startAt},OR:[{taskId:null},{task:{deletedAt:null}}]},select:{id:true,title:true}}),db.event.findMany({where:{userId,deletedAt:null,startAt:{lt:endAt},endAt:{gt:startAt}},select:{id:true,title:true}})]);return[...blocks,...events]}
export async function createTimeBlock(userId:string,input:TimeBlockInput){if(!await taskAvailable(userId,input.taskId))throw new TimeBlockRuleError("Tugas yang dipilih tidak tersedia.");const t=times(input);return db.timeBlock.create({data:{userId,taskId:input.taskId,title:input.title,...t}})}
export async function updateTimeBlock(userId:string,id:string,input:TimeBlockInput){if(!await taskAvailable(userId,input.taskId))throw new TimeBlockRuleError("Tugas yang dipilih tidak tersedia.");const r=await db.timeBlock.updateMany({where:{id,userId,deletedAt:null},data:{taskId:input.taskId,title:input.title,...times(input)}});return r.count===1}
export async function deleteTimeBlock(userId:string,id:string){return(await db.timeBlock.updateMany({where:{id,userId,deletedAt:null},data:{deletedAt:new Date()}})).count===1}
export async function dismissReschedule(userId:string,id:string){return(await db.timeBlock.updateMany({where:{id,userId,deletedAt:null,rescheduleState:"NONE",taskId:{not:null},endAt:{lt:new Date()},task:{userId,deletedAt:null,status:{not:"DONE"}}},data:{rescheduleState:"DISMISSED"}})).count===1}
export async function rescheduleTimeBlock(userId:string,id:string,date:string,startTime:string,endTime:string){const startAt=jakartaDateTime(date,startTime),endAt=jakartaDateTime(date,endTime);if(!Number.isFinite(startAt.getTime())||!Number.isFinite(endAt.getTime())||endAt<=startAt)throw new TimeBlockRuleError("Waktu selesai harus setelah waktu mulai.");return db.$transaction(async tx=>{const old=await tx.timeBlock.findFirst({where:{id,userId,deletedAt:null,rescheduleState:"NONE",taskId:{not:null},endAt:{lt:new Date()},task:{userId,deletedAt:null,status:{not:"DONE"}}}});if(!old)return null;const claimed=await tx.timeBlock.updateMany({where:{id,userId,deletedAt:null,rescheduleState:"NONE"},data:{rescheduleState:"RESCHEDULED"}});if(claimed.count!==1)return null;return tx.timeBlock.create({data:{userId,taskId:old.taskId,title:old.title,startAt,endAt,rescheduledFromId:old.id}})})}
