import Link from "next/link";
import { TaskDiscoveryForm } from "@/components/task-discovery-form";
import { TaskForm } from "@/components/task-forms";
import { requireUser } from "@/lib/auth/session";
import { jakartaDate } from "@/lib/date/jakarta";
import { activeFilterCount, parseTaskDiscovery } from "@/lib/validation/task-discovery";
import { createTaskAction } from "@/server/actions/tasks";
import { countActiveTasks, getFilteredTasks, getTaskDiscoveryOptions } from "@/server/queries/task-queries";
import { isTaskOverdue, taskProgress } from "@/server/services/task-service";

export default async function TasksPage({searchParams}:{searchParams:Promise<Record<string,string|string[]|undefined>>}){const[user,params]=await Promise.all([requireUser(),searchParams]),filters=parseTaskDiscovery(params),now=new Date(),today=jakartaDate(now);const[tasks,options,total]=await Promise.all([getFilteredTasks(user.id,filters,now,today),getTaskDiscoveryOptions(user.id),countActiveTasks(user.id)]),active=activeFilterCount(filters);return <main className="mx-auto max-w-6xl px-4 py-10 sm:px-6"><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-semibold text-emerald-700">DO</p><h1 className="mt-2 text-4xl font-semibold">Tasks</h1><p className="mt-2 text-slate-600">Temukan dan prioritaskan pekerjaan yang perlu diselesaikan.</p></div><Link href="/trash" className="min-h-11 rounded-lg border bg-white px-4 py-2.5 font-semibold">Buka Trash</Link></header><TaskDiscoveryForm filters={filters} projects={options.projects} areas={options.areas} count={active}/><details className="mt-6 rounded-2xl border border-slate-200 bg-white p-6"><summary className="cursor-pointer font-semibold">+ Tambah tugas</summary><div className="mt-6"><TaskForm action={createTaskAction} projects={options.projects}/></div></details><section className="mt-8 space-y-3">{tasks.length===0?<div className="rounded-2xl border border-dashed border-slate-300 p-8 text-center">{total&&active?<><p className="font-medium">Tidak ada task yang cocok dengan pencarian atau filter.</p><Link href="/tasks" className="mt-2 inline-block font-semibold text-emerald-800">Clear filters</Link></>:<><p className="font-medium">Belum ada tugas.</p><p className="mt-1 text-sm text-slate-600">Tambahkan tugas pertama agar kamu tahu apa yang perlu dikerjakan.</p></>}</div>:tasks.map(task=>{const progress=taskProgress(task),overdue=isTaskOverdue(task,now);return <Link key={task.id} href={`/tasks/${task.id}`} className="block rounded-xl border border-slate-200 bg-white p-5 hover:border-slate-400"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{task.title}</h2><p className="mt-1 text-sm text-slate-500">{task.project?.name??"Tanpa project"} · {task.priority} · {task.status}</p></div><div className="text-right"><p className="font-semibold">{progress.progress}%</p>{overdue?<p className="text-sm font-medium text-red-700">Terlambat</p>:null}</div></div>{task.deadlineAt?<p className="mt-3 text-sm text-slate-500">Deadline {new Intl.DateTimeFormat("id-ID",{dateStyle:"medium",timeStyle:"short",timeZone:"Asia/Jakarta"}).format(task.deadlineAt)}</p>:null}</Link>})}</section></main>}
